#!/bin/sh

# author : denzfarid <farid_@msn.com>
# 14-des-2017
# jenkins build script for 2 branch master and staging


echo -e "\n\n[!] Detected branch in ${GIT_BRANCH} "
case  "${GIT_BRANCH}"  in

     'origin/master')
        # for master branch
		echo "Pulling prod, please wait .."
		ssh root@[SERVER-IP] 'cd /var/www/html/ || exit; unset GIT_DIR; git fetch && git add --all && git reset --hard origin/master'
        ;;
        
     'origin/staging')
        # for staging branch
        echo "Pulling stage, please wait .."
		ssh root@[SERVER-IP] 'cd /var/www/html/ || exit; unset GIT_DIR; git fetch && git add --all && git reset --hard origin/staging'
        ;;
        
esac
