#!/bin/sh

# author : denzfarid <farid_@msn.com>
# 14-des-2017
# jenkins build script for 2 branch master and staging


echo -e "\n\n[!] Detected branch in ${GIT_BRANCH} "
case  "${GIT_BRANCH}"  in

     'origin/master')
        # for master branch
		echo "Pulling prod, please wait .."
		ssh root@[SERVER-IP] 'ansible-playbook /etc/ansible/playbook/production.yml --flush-cache' #webserver.yml
        ;;
        
     'origin/staging')
        # for staging branch
        echo "Pulling stage, please wait .."
		ssh root@[SERVER-IP] 'ansible-playbook /etc/ansible/playbook/staging.yml --flush-cache' #webserver.yml
        ;;
#or you can use 1 file webserver.ym
        
esac
