- hosts: IP-STAGING
  remote_user: ec2-user
  tasks:
  - name: Pulling staging, please wait ..
    action: shell cd /var/www/public_html/ || exit; unset GIT_DIR; git fetch && git add --all && git reset --hard origin/staging


#if you use tag you can change hosts ip to tag_NAME          
